name: Linux CI Workflow
on: [push]
jobs:
  # build-and-test:
  #   name: Build and run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout current repository in ubuntu's file system 
  #       uses: actions/checkout@v1
  #     - name: Setup JDK 1.8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Print contents in current directory
  #       run: ls -la
  #     - name: Change wrapper permissions
  #       run: chmod +x ./gradlew
  #       working-directory: ./SimpleCalculator/starter
  #     - name: Unit tests
  #       run: ./gradlew testDebugUnitTest
  #       working-directory: ./SimpleCalculator/starter

  generate-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    # needs:
    #   - build-and-test
    steps:
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        working-directory: ./SimpleCalculator/starter

      - name: Generate apk
        run: ./gradlew assembleDebug
        working-directory: ./SimpleCalculator/starter

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: ./SimpleCalculator/starter/app/build/outputs/apk/debug/app-debug.apk

      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: taeyh/AndroidSimpleCalculator
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: Collaborators
          file: ./SimpleCalculator/starter/app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: false




