name: mac os CI Workflow
on: [pull_request]
jobs:
  build-and-test:
    name: Build and run tests
    # runs-on: ubuntu-latest
    runs-on: macos-latest # Switched to macOS
    steps:
      - uses: actions/checkout@v2
      - name: Print contents in current directory
        run: ls -ale

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        working-directory: ./SimpleCalculator/starter

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
        working-directory: ./SimpleCalculator/starter

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
          working-directory: ./SimpleCalculator/starter
